import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%KOLUX_AGENT_HOOK_PORT%"=="" if defined KOLUX_AGENT_HOOK_ENDPOINT if exist "%KOLUX_AGENT_HOOK_ENDPOINT%" call "%KOLUX_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%KOLUX_AGENT_HOOK_TOKEN%"=="" if not "%KOLUX_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\kolux-dev\\agent-hooks" for /r "%APPDATA%\\kolux-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%KOLUX_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\kolux\\agent-hooks" for /r "%APPDATA%\\kolux\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%KOLUX_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set KOLUX_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%KOLUX_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__kolux_read_ancestor_var() {',
    '  __kolux_name="$1"',
    '  __kolux_pid="${PPID:-}"',
    '  while [ -n "$__kolux_pid" ] && [ "$__kolux_pid" != "0" ] && [ "$__kolux_pid" != "1" ]; do',
    '    __kolux_value=""',
    '    if [ -r "/proc/$__kolux_pid/environ" ]; then',
    '      __kolux_value=$(tr "\\000" "\\n" < "/proc/$__kolux_pid/environ" 2>/dev/null | sed -n "s/^${__kolux_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__kolux_value" ]; then',
    '      __kolux_value=$(ps eww -p "$__kolux_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__kolux_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__kolux_value" ]; then',
    '      printf "%s\\n" "$__kolux_value"',
    '      return 0',
    '    fi',
    '    __kolux_pid=$(ps -o ppid= -p "$__kolux_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__kolux_fill_from_ancestor() {',
    '  __kolux_name="$1"',
    '  case "$__kolux_name" in',
    '    KOLUX_AGENT_HOOK_ENDPOINT) [ -z "${KOLUX_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    KOLUX_AGENT_HOOK_PORT) [ -z "${KOLUX_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    KOLUX_AGENT_HOOK_TOKEN) [ -z "${KOLUX_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    KOLUX_AGENT_HOOK_ENV) [ -z "${KOLUX_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    KOLUX_AGENT_HOOK_VERSION) [ -z "${KOLUX_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    KOLUX_PANE_KEY) [ -z "${KOLUX_PANE_KEY:-}" ] || return 0 ;;',
    '    KOLUX_TAB_ID) [ -z "${KOLUX_TAB_ID:-}" ] || return 0 ;;',
    '    KOLUX_WORKTREE_ID) [ -z "${KOLUX_WORKTREE_ID:-}" ] || return 0 ;;',
    '    KOLUX_AGENT_LAUNCH_TOKEN) [ -z "${KOLUX_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __kolux_value=$(__kolux_read_ancestor_var "$__kolux_name") || return 0',
    '  [ -n "$__kolux_value" ] && export "$__kolux_name=$__kolux_value"',
    '}',
    '__kolux_endpoint_value() {',
    '  __kolux_endpoint_name="$1"',
    '  __kolux_endpoint_path="$2"',
    '  sed -n "s/^${__kolux_endpoint_name}=//p" "$__kolux_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__kolux_fill_from_endpoint_file() {',
    '  __kolux_endpoint_path="$1"',
    '  [ -r "$__kolux_endpoint_path" ] || return 0',
    '  __kolux_endpoint_port=$(__kolux_endpoint_value KOLUX_AGENT_HOOK_PORT "$__kolux_endpoint_path")',
    '  if [ -n "${KOLUX_AGENT_HOOK_PORT:-}" ] && [ -n "$__kolux_endpoint_port" ] && [ "$__kolux_endpoint_port" != "$KOLUX_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __kolux_endpoint_name in KOLUX_AGENT_HOOK_PORT KOLUX_AGENT_HOOK_TOKEN KOLUX_AGENT_HOOK_ENV KOLUX_AGENT_HOOK_VERSION; do',
    '    eval "__kolux_current=\\${$__kolux_endpoint_name:-}"',
    '    [ -z "$__kolux_current" ] || continue',
    '    __kolux_endpoint_value=$(__kolux_endpoint_value "$__kolux_endpoint_name" "$__kolux_endpoint_path")',
    '    [ -n "$__kolux_endpoint_value" ] && export "$__kolux_endpoint_name=$__kolux_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Kolux pane/hook metadata, so recover it before posting.',
    'for __kolux_name in KOLUX_AGENT_HOOK_ENDPOINT KOLUX_AGENT_HOOK_PORT KOLUX_AGENT_HOOK_TOKEN KOLUX_AGENT_HOOK_ENV KOLUX_AGENT_HOOK_VERSION KOLUX_PANE_KEY KOLUX_TAB_ID KOLUX_WORKTREE_ID KOLUX_AGENT_LAUNCH_TOKEN; do',
    '  __kolux_fill_from_ancestor "$__kolux_name"',
    'done',
    'if [ -n "$KOLUX_AGENT_HOOK_ENDPOINT" ] && [ -r "$KOLUX_AGENT_HOOK_ENDPOINT" ]; then',
    '  __kolux_fill_from_endpoint_file "$KOLUX_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# KOLUX_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$KOLUX_AGENT_HOOK_TOKEN" ] && [ -n "$KOLUX_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/kolux-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/kolux-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kolux-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kolux-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/kolux/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kolux/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^KOLUX_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$KOLUX_AGENT_HOOK_PORT" ]; then',
    '      __kolux_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$KOLUX_AGENT_HOOK_PORT" ] || [ -z "$KOLUX_AGENT_HOOK_TOKEN" ] || [ -z "$KOLUX_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${KOLUX_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Kolux-Agent-Hook-Token: ${KOLUX_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${KOLUX_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${KOLUX_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${KOLUX_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${KOLUX_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${KOLUX_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${KOLUX_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
