export function getStatusPluginV2EventAdapterSource(): string[] {
  return [
    '// Why: OpenCode 2.x replaced the V1 event model — payloads moved from',
    '// `event.properties` to `event.data`, `question.*` became `form.*`, and the',
    '// `message.*` family was deleted in favour of `session.text.*` / `session.inbox.*`.',
    '// The handler above still speaks V1 (every behavioural test drives it that way),',
    '// so translate once here instead of scattering the renames through lifecycle,',
    '// ownership and preview.',
    'const V2_ASSISTANT_TEXT_LIMIT = 128;',
    'const v2AssistantTextByKey = new Map();',
    '',
    'function v2TextKey(sessionID, messageID, ordinal) {',
    '  return JSON.stringify([sessionID || "", messageID || "", ordinal || 0]);',
    '}',
    '',
    'function rememberV2AssistantText(key, text) {',
    '  if (v2AssistantTextByKey.size >= V2_ASSISTANT_TEXT_LIMIT && !v2AssistantTextByKey.has(key)) {',
    '    const first = v2AssistantTextByKey.keys().next().value;',
    '    if (first !== undefined) v2AssistantTextByKey.delete(first);',
    '  }',
    '  v2AssistantTextByKey.set(key, text);',
    '}',
    '',
    '// Why: the dashboard card renders the AskUserQuestion input shape (`{ questions }`),',
    '// which is what `deriveInteractivePrompt` stringifies, so project V2 form fields',
    '// into it — shipping the raw form leaves the card unable to read its own payload.',
    'function formToQuestions(form) {',
    '  const fields = Array.isArray(form?.fields) ? form.fields : [];',
    '  return fields.filter((field) => field && field.hidden !== true).map((field) => ({',
    '    question: field.title || field.key,',
    '    header: field.title || field.key,',
    '    multiSelect: field.type === "multiselect",',
    '    options: (Array.isArray(field.options) ? field.options : []).map((option) => ({',
    '      label: option?.label || option?.value || "",',
    '      description: option?.description || ""',
    '    }))',
    '  }));',
    '}',
    '',
    'function v2ToV1Events(event) {',
    '  if (!event || typeof event.type !== "string") return [];',
    '  const data = event.data && typeof event.data === "object" ? event.data : {};',
    '  switch (event.type) {',
    '    case "session.status":',
    '    case "session.idle":',
    '    case "permission.asked":',
    '    case "permission.replied":',
    '      return [{ type: event.type, properties: data }];',
    '    case "session.created":',
    '      // Why: V2 dropped the `info` envelope but kept `parentID`; rebuild it so the',
    '      // SessionStart root check and the root cache keep their original shape.',
    '      return [{',
    '        type: "session.created",',
    '        properties: { info: { id: data.sessionID, parentID: data.parentID } }',
    '      }];',
    '    case "session.execution.failed":',
    '    case "session.compaction.failed":',
    '      // Why: V2 split V1 session.error into per-step and per-execution failures;',
    '      // only completion is authoritative, so both stay the deliberate no-op.',
    '      return [{ type: "session.error", properties: data }];',
    '    case "form.created": {',
    '      const form = data.form || {};',
    '      return [{',
    '        type: "question.asked",',
    '        properties: {',
    '          id: form.id,',
    '          sessionID: form.sessionID,',
    '          title: form.title,',
    '          fields: form.fields,',
    '          questions: formToQuestions(form)',
    '        }',
    '      }];',
    '    }',
    '    case "form.replied":',
    '      return [{',
    '        type: "question.replied",',
    '        properties: { id: data.id, sessionID: data.sessionID, requestID: data.id }',
    '      }];',
    '    case "form.cancelled":',
    '      return [{',
    '        type: "question.rejected",',
    '        properties: { id: data.id, sessionID: data.sessionID, requestID: data.id }',
    '      }];',
    '    case "session.inbox.enqueued": {',
    '      const item = data.item;',
    '      // Why: only a user prompt becomes the pane preview; synthetic/compaction',
    '      // items are OpenCode machinery it also hides from its own prompt.',
    '      if (!item || item.type !== "user") return [];',
    '      const text = item.payload?.text;',
    '      if (!text) return [];',
    '      const messageID = data.inboxID;',
    '      return [',
    '        { type: "message.updated", properties: { info: { id: messageID, role: "user" } } },',
    '        {',
    '          type: "message.part.updated",',
    '          properties: {',
    '            sessionID: data.sessionID,',
    '            part: { type: "text", text, messageID }',
    '          }',
    '        }',
    '      ];',
    '    }',
    '    case "session.text.started":',
    '      rememberV2AssistantText(',
    '        v2TextKey(data.sessionID, data.assistantMessageID, data.ordinal),',
    '        ""',
    '      );',
    '      return [',
    '        { type: "message.updated", properties: { info: { id: data.assistantMessageID, role: "assistant" } } }',
    '      ];',
    '    case "session.text.delta": {',
    '      // Why: V2 streams incremental deltas where V1 re-sent the whole part, so the',
    '      // preview queue still needs one accumulated snapshot per text block.',
    '      const delta = typeof data.delta === "string" ? data.delta : "";',
    '      const key = v2TextKey(data.sessionID, data.assistantMessageID, data.ordinal);',
    '      const accumulated = (v2AssistantTextByKey.get(key) || "") + delta;',
    '      rememberV2AssistantText(key, accumulated);',
    '      return [',
    '        { type: "message.updated", properties: { info: { id: data.assistantMessageID, role: "assistant" } } },',
    '        {',
    '          type: "message.part.delta",',
    '          properties: { sessionID: data.sessionID, field: "text", delta }',
    '        },',
    '        {',
    '          type: "message.part.updated",',
    '          properties: {',
    '            sessionID: data.sessionID,',
    '            part: { type: "text", text: accumulated, messageID: data.assistantMessageID }',
    '          }',
    '        }',
    '      ];',
    '    }',
    '    case "session.text.ended": {',
    '      v2AssistantTextByKey.delete(',
    '        v2TextKey(data.sessionID, data.assistantMessageID, data.ordinal)',
    '      );',
    '      const role = { type: "message.updated", properties: { info: { id: data.assistantMessageID, role: "assistant" } } };',
    '      if (!data.text) return [role];',
    '      return [',
    '        role,',
    '        {',
    '          type: "message.part.updated",',
    '          properties: {',
    '            sessionID: data.sessionID,',
    '            part: { type: "text", text: data.text, messageID: data.assistantMessageID }',
    '          }',
    '        }',
    '      ];',
    '    }',
    '    default:',
    '      return [];',
    '  }',
    '}',
    '',
    '// Why: OpenCode fires hooks without awaiting them and the handler\'s own lifecycle',
    '// FIFO preserves order — awaiting here would let one slow Kolux post stall the',
    '// whole event stream.',
    'function dispatchV1Event(hooks, event) {',
    '  try {',
    '    const result = hooks && typeof hooks.event === "function" ? hooks.event({ event }) : undefined;',
    '    if (result && typeof result.catch === "function") result.catch(() => {});',
    '  } catch {',
    '    // Hook delivery must never reject into OpenCode.',
    '  }',
    '}',
    ''
  ]
}
